// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vbu2tRSZX-k0l2XM-lvDRkrtaPQHauE',
    appId: '1:111153909184:android:1ab68a060422aca16b0c25',
    messagingSenderId: '111153909184',
    projectId: 'admin-app-1f284',
    storageBucket: 'admin-app-1f284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cqui4lwsUNYv48lNPelocKrmIYbBkYM',
    appId: '1:111153909184:ios:4e153a189dc552e86b0c25',
    messagingSenderId: '111153909184',
    projectId: 'admin-app-1f284',
    storageBucket: 'admin-app-1f284.firebasestorage.app',
    androidClientId: '111153909184-08mqjnfrd1hav0584060otf117s2joot.apps.googleusercontent.com',
    iosClientId: '111153909184-7d9jdaj0pi7qc0vkho060et2o7r5e3em.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionAdminApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7g1b2a0vk1bv7R-Vfq2QGPbHPmhEyaqw',
    appId: '1:111153909184:web:36aa9548469970036b0c25',
    messagingSenderId: '111153909184',
    projectId: 'admin-app-1f284',
    authDomain: 'admin-app-1f284.firebaseapp.com',
    storageBucket: 'admin-app-1f284.appspot.com',
  );

}